### ISSUE TITLE
OSX GUI Wallet (OSX 10.9.5) CONSOLE doesn't work

### ISSUE THREAD

**Issue by jazy510** [expanse-org/expwallet#3]
I press the "CONSOLE" button, and the lower half of the app blanks out, and redraws a text display, with the error message: "No such file or directory"

Then, when i attempt to issue a console command, it simply concatenates the text onto the end, and doesn't do anything, eg:

"No such file or directoryweb3.version"

**Comment by chrisfranko** [comment]
this wallet isnt the one we actually ended up using but will soon be releasing a new one,i should take this repo down.
